FROM debian:bookworm-slim
LABEL maintainer="SmartBugs Project <https://github.com/smartbugs/oyente"

ARG SOLC_VERSION=0.8.30
ENV SOLC_VERSION=${SOLC_VERSION}
ENV VENV=/root/venv
ENV PATH="$VENV/bin:$PATH"

# Install Python 3.11 (pinned) and other deps
RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        python3=3.11* \
        python3-pip \
        python3-venv \
        git \
    && python3 -m venv $VENV \
    && pip install --no-cache-dir --upgrade pip wheel \
    && pip install --no-cache-dir \
        cbor2 \
        crytic-compile==0.3.8 \
        requests \
        six \
        solc-select \
        typing_extensions \
        z3-solver==4.14.1.0 \
    && pip install --no-cache-dir git+https://github.com/gsalzer/ethutils.git@main#egg=ethutils \
    && apt remove -y git \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Install chosen solidity compiler version
RUN solc-select install ${SOLC_VERSION}

# Copy and initialize Oyente
COPY ./oyente /oyente/
WORKDIR /oyente
RUN python3 -O -m compileall -f /oyente

ENTRYPOINT ["python3", "/oyente/oyente.py"]
